[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
crossterm = "0.28.1"
itertools = "0.13.0"
regex = "1.11.1"
rayon = "1.10.0"
